# Generated by Django 4.1.5 on 2023-01-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blogodel',
            new_name='BlogModel',
        ),
    ]
